### ISSUE TITLE
G55，日志没发现有报错，操作完设备列表还是没有设备

### ISSUE THREAD

**Issue by LiangPG** [stevenjoezhang/hass-iotbull#4]
[home-assistant_bull_2023-11-27T04-59-22.708Z.log](https://github.com/stevenjoezhang/hass-iotbull/files/13470092/home-assistant_bull_2023-11-27T04-59-22.708Z.log)

**Comment by LiangPG** [comment]
搞定了 G55开关，globalProductId添加34, 35, 36

**Comment by stevenjoezhang** [comment]
谢谢反馈，已更新： 853e81c2cb9c868c0b0e3b651a5e8caf391ad829
