### ISSUE TITLE
使用这个链接可以通过HACS直接一键安装

### ISSUE THREAD

**Issue by CGNing** [stevenjoezhang/hass-iotbull#7]
[![通过HACS添加集成](https://my.home-assistant.io/badges/hacs_repository.svg)](https://my.home-assistant.io/redirect/hacs_repository/?owner=stevenjoezhang&repository=hass-iotbull&category=integration)

**Comment by stevenjoezhang** [comment]
谢谢提醒，因为我自己的hass环境用的docker版本，所以一直没怎么用HACS。我会把这个按钮链接加到Readme里面。
